language: go

sudo: false

go:
  - 1.6.2
  - tip

services:
  - memcached
  - redis-server

addons:
  apt:
    packages:
      - graphicsmagick

before_install:
  - go get -v github.com/golang/lint/golint

install: go get -v -d -t ./...

script:
  - "echo 'mode: atomic' > coverage.txt && go list ./... | xargs -n1 -I{} sh -c 'go test -covermode=atomic -coverprofile=coverage.tmp {} && tail -n +2 coverage.tmp >> coverage.txt' && rm coverage.tmp"
  - gofmt -d .
  - go tool vet .
  - golint ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
